config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, :only => [:show] do
    resources :items, :only => [:create, :destroy]
  end

  root 'users#show'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  validates :name, length: { minimum: 3 }, presence: true
  validates :user, presence: true

  scope :visible_to, ->(user) { user ? all : where(public: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items

  before_save { self.role ||= :member }

  enum role: [:member]

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(email).downcase # rubocop:disable ColonMethodCall
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(*)
    current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was saved successfully."
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
    end
    redirect_to root_path
  end

  def destroy
    @item = current_user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "\"#{@item}\" was deleted successfully."
    else
      flash.now[:alert] = "There was an error deleting the item."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :user_id, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item], remote: true do |f| %>
<div class="bootstrap-iso">
 <div class="container-fluid">
  <div class="row">
   <div class="col-md-6 col-sm-6 col-xs-12">
    <form method="post">
      <div class="form-group" style="font-family: 'Josefin Sans', sans-serif;">
        <h3><%= f.label :task %></h3>
        <%= f.text_area :name, class: 'form-control', placeholder: "Enter item here" %>
        <h6 style="color:grey"><span class="help-block" id="hint_textarea">
         Create your daily to do list. If you don't complete an item within 7 days, we'll whack it for you (it shouldn't be on your daily to do list anyway)!
        </span></h6>
      </div>
      <div class="form-group">
        <%= f.submit "Add", class: 'btn btn-success' %>
      </div>
<% end %>

app/views/items/_item.html.erb
<div class="media">
  <div class="media-body">
    <h3 id="item-header" class="media-heading">
      <%= link_to "", user_item_path(@user, item), method: :delete, remote: true, id: "foo#{item.id}", class: 'glyphicon glyphicon-unchecked', onmousedown: "$('#foo#{item.id}').removeClass('glyphicon-unchecked').addClass('glyphicon-ok')" %>
      <%= item.name %>
    </h3>
    <h6 class="media-heading">
      <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %> left!
    </h6>
  </div>
</div>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
   $('#item-<%= @item.id %>').hide();
   $(document).ajaxStop(function(){window.location.reload();});
 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task Tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:700" rel="stylesheet" type="text/css">
  <!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
  <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

  <!-- Inline CSS based on choices in "Settings" tab -->
  <style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>

</head>
<body>
  <nav class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-header">
      <h3 style="font-weight:bold;color:white;font-family: 'Josefin Sans', sans-serif;">Task Tracker</h3>
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to('', '#') %></li>
				<li><%= link_to('', '#') %></li>
				<li><%= link_to('', '#') %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to('My Account', edit_user_registration_path) %></li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				<% else %>
					<li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %>
				<% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.container-fluid -->
</nav>
  <%= yield %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4 pull-right">
    <div class="media">
      <br />
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-right">
          <%= image_tag avatar_url, class: 'media-object' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="add-item" style="font-family: 'Josefin Sans', sans-serif;">
<%= render partial: 'items/form', locals: { user: @user, item: Item.new } %>
</div>

<div class="bootstrap-iso">
 <div class="container-fluid">
  <div class="row">
   <div class="col-md-6 col-sm-6 col-xs-12">
     <div class="item-list" style="font-family: 'Josefin Sans', sans-serif;">
       <h3 style="font-weight:bold;">Your Tasks</h3>
       <h6 class="media-heading" style="color:grey">Check completed items as done!</h6>
        <div class='js-items'>
          <%= render @user.items %>
        </div>
      </div>
    </div>
  </div>
</div>